config/routes.rb
Rails.application.routes.draw do
 
  resources :sessions, only: [:new, :create, :destroy]
  resources :useractions, only: [:create, :index, :show]

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'history', to: 'useractions#history', as: 'history'

  resources :users
  get 'page/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "level1#lvl1"
  get 'lvl1' => 'level1#lvl1'
  get 'lvl2' => 'level2#lvl2'
  get 'lvl3' => 'level3#lvl3'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

 validates :first_name, presence: true

end

app/models/useraction.rb
class Useraction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    User.where(id: session[:user_id]).first
  end

  helper_method :current_user

end

app/controllers/level1_controller.rb
class Level1Controller < ApplicationController
  def lvl1
  end
end

app/controllers/level2_controller.rb
class Level2Controller < ApplicationController
  def lvl2
  end
end

app/controllers/level3_controller.rb
class Level3Controller < ApplicationController
  def lvl3
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/useractions_controller.rb
class UseractionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @useraction = Useraction.new
  end

  def create
    @useraction = Useraction.new(user_id: current_user.first_name, level: params[:level], action_category: params[:category], action_details: params[:details])
    respond_to do |format|
      @useraction.save
      format.html { redirect_to root_url }
      format.json {render :show, status: :created, location: @useraction }
    end
  end

  def destroy
  end

  def history 
    @history = Useraction.where('user_id = ? AND level = ? AND action_category = ?', current_user.first_name, 'level3', 'solution').order('id DESC').limit(5)
    respond_to do |format|
      #format.html { redirect_to root_url }
      format.json {render json: @history, status: :ok }
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/useraction_helper.rb
module UseractionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Algoworld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %> 
    <%= stylesheet_link_tag "jquery-ui_1.13.1.min" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "jquery_2.1.4_jquery.min" %>
    <%= javascript_include_tag "jquery-ui_1.13.1.min" %>
    <%= javascript_include_tag "createjs.min" %>
    <%= javascript_include_tag "tweenjs.min" %>
    <%= javascript_include_tag "cek3iwo" %>
    <%= yield(:head) %>
  </head>

  <body onload="init();">
  
<div id="user_header">
  <% if current_user %>
    Welcome, <span id="uname"><%= current_user.first_name %></span>.
    <%= link_to "Account", edit_user_path(current_user) %>
    <%= link_to "Log Out", logout_path %>
    <span id="current_user" style="display:none"><%= current_user.first_name %></span>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>
 </div>

 <% flash.each do |key, value| %>
  <%= content_tag(:div, class: "alert alert-#{key}") do %>
    <p><%= value %></p>
  <% end %>
 <% end %>

<%= yield %>

  </body>
</html>

app/views/level1/lvl1.html.erb
<% content_for :head do %>
    <%= javascript_include_tag "lvl1World"  %>
<% end %>
<table>
        <tr>
            <td>
                Levels:
            
                <button id="lvl1Button" > _1_ </button>
                <a href="lvl2"><button id="lvl2Button" > _2_ </button></a>
                <a href="lvl3"><button id="lvl3Button" > _3_ </button></a>
                
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
        <tr>
            <td>
                <p>Instructions:</p>
                <span class="level1">Drag the instructions into available slots and help keep pedestrians and cars moving.</span>
                <br/>
                <canvas id="myWorldCanvas" width="1100" height="450"></canvas>
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
        <tr>
            <td>
                
            </td>
        </tr>
    
    </table>

app/views/level2/lvl2.html.erb
<% content_for :head do %>
    <%= javascript_include_tag "lvl2World"  %>
<% end %>
<table>
        <tr>
            <td>
                Levels:
               
                <a href="lvl1"><button id="lvl1Button" > _1_ </button></a>
                <button id="lvl2Button" > _2_ </button>
                <a href="lvl3"><button id="lvl3Button" > _3_ </button></a>
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
        <tr>
            <td>
                <h1>Teacher of the Year Award!</h1>
                <p>Instructions:</p>
                <span class="level2"><ul><li>Click on each teacher to learn about them. </li><li>Use the sliders on the right to decide which attributes are most important</li><li> Click go to see who wins Teacher of the Year</li></ul></span>
                <br/>
                <canvas id="myWorldCanvas" width="700" height="550"></canvas>
            </td>
            <td>
                
            </td>
          
            
            <td class="level2">
                <table class="sliderTable">
                    <tr>
                        <td>
                            <p>Choose how important each of these traits should be in granting the Teacher of the Year award.</p> <br>
                            <b><-- Less Important ____________ More Important --> </b> <br>
                            <span class="sliderBox" id="degreeSliderBox">Degree<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="degreeSlider">
                            </span>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="sliderBox" id="attendanceSliderBox">Attendance<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="attendanceSlider">
                            </span>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="sliderBox" id="kindnessSliderBox">Kindness<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="kindnessSlider">
                            </span>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="sliderBox" id="coolfactorSliderBox">Cool Factor<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="coolfactorSlider">
                            </span>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="sliderBox" id="testscoresSliderBox">Test Scores<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="testscoresSlider">
                            </span>
                            
                        </td>
                        
                    </tr>
                    <tr>
                        
                        <td>
                            <span class="sliderBox" id="genderSliderBox">Gender<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="genderSlider">
                            </span>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="sliderBox" id="raceSliderBox">Race<br/>
                                <input type="range" min="1" max="100" value="50" class="slider" id="raceSlider">
                            </span>
                            
                        </td>
                    </tr>
                   
                
                    <tr>
                        <td>
                            <button id="eventButton" >GO!</button>
                        </td>
                    </tr>
                </table>
                
            </td>
        </tr>
        <tr>
            <td>
            
            </td>
        </tr>
    </table>

app/views/level3/lvl3.html.erb
<% content_for :head do %>
    <%= javascript_include_tag "lvl3World"  %>
<% end %>
<table>
        <tr>
            <td>
                Levels:
            
                <a href="lvl1"><button id="lvl1Button" > _1_ </button></a>
                <a href="lvl2"><button id="lvl2Button" > _2_ </button></a>
                <button id="lvl3Button" > _3_ </button>
            </td>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
        <tr>
            <td>
                <div class="awDialog" id="dialog10" title="Level 3: Algo-World live!" style="width:400">
                    <p>Algorithms are everywhere in real life! They help decide who gets a job, who gets a bank loan, and who has to go to Prison. Sometimes, the data available to those algorithms results in some bad choices. Now YOU get to choose the data available to banks, employers, and prisons and watch who can manage to avoid extreme poverty. </p>
                </div>
                
                <p>Instructions:</p>
                <span class="level3">Algorithms are everywhere in real life! They help decide who gets a job, <br>who gets a bank loan, and who has to go to Prison. Sometimes, the data <br>available to those algorithms results in some bad choices. <br>Choose the data available to banks, employers, and prisons and watch <br>who can manage to avoid extreme poverty.</span>
                <br/>
                <canvas id="myWorldCanvas" width="500" height="500"></canvas>
            </td>
            
            <td>
                <div id="eventResults" class="level3">
                    <div class="lvl3Results">
                        <h2>Results:</h2>
                        <p>Extreme Poverty:</p>
                        <p>White: <span id="mortalityRaceWhite">30</span>%<br/>Color: <span id="mortalityRaceColor">70</span>%</p>
                        <p>Male: <span id="mortalityGenderMale">20</span>%<br/>Female: <span id="mortalityGenderFemale">80</span>%</p>
                    
                    <!-- commented this statistic group out because it was distracting / confusing.

                    <p>Wealth Distribution among others: (per person)</p>
                    <p>White: <i class="fa fa-btc"></i><span id="wealthRaceWhite">30</span><br/>Color: <i class="fa fa-btc"></i><span id="wealthRaceColor">70</span></p>
                    <p>Male: <i class="fa fa-btc"></i><span id="wealthGenderMale">20</span><br/>Female: <i class="fa fa-btc"></i><span id="wealthGenderFemale">80</span></p>
                  //-->  
                    </div>
                </div>
                <div class="level3">
                    <p>Speed: <span id="currentSpeedLabel">50</span></p>
                    <div class="slidecontainer">
                        <input type="range" min="1" max="100" value="50" class="slider" id="speedSlider">
                    </div>
                    <div>
                        <button id="pauseButton">PAUSE</button>
                    </div>
                    <div>
                        <button id="goButton">Start Over</button>
                    </div>
                </div>
            </td>

            <td class="level3">
                <div class="level3">
                        <div class="lvl3CompanySelectors">
                            <u><b>Data for Job Application</b></u><br>
                            <p class="tab"></p>
                            <b>Web History</b><br>
                            <input type="checkbox" id="jobAmazon" checked>Amazon Purchases<br>
                            <p class="tab"></p>
                            <b>Personal Records</b><br>
                            
                            <input type="checkbox" id="jobRace" checked >Race<br>
                            <input type="checkbox" id="jobGender"  checked >Gender<br>
                            <input type="checkbox" id="jobSexuality" checked >Sexuality<br>
                            <input type="checkbox" id="jobCrimes" checked>Criminal Record<br><p></p>
                            
                            <b>Financial Data</b><br>
                           
                            <input type="checkbox" id="jobSalary"  checked>Current Salary<br>
                            
                        </div>
                </div>
            </td>
            <td class="level3">
                <div class="level3">
                    
                    
                        
                    <div class="lvl3BankSelectors">
                        <u><b>Data for Bank Loan</b></u><br>
                        <p class="tab"></p>
                        <b>Web History</b><br>
                        <input type="checkbox" id="bnkAmazon" checked>Amazon Purchases<br>
                        <p class="tab"></p>
                        <b>Personal Records</b><br>
                        
                        <input type="checkbox" id="bnkRace"  checked>Race<br>
                        <input type="checkbox" id="bnkGender"  checked>Gender<br>
                        <input type="checkbox" id="bnkSexuality"  checked>Sexuality<br>
                        <input type="checkbox" id="bnkCrimes"  checked >Criminal Record<br><p></p>
                        
                        <b>Financial Data</b><br>
                        
                        <input type="checkbox" id="bnkSalary"  checked>Current Salary<br>
                        
                    </div>
                </div>
            </td>
            <td class="level3">
                <div class="level3">            
                        <div class="lvl3PrisonSelectors">
                            <u><b>Data for Prison Sentence</b></u><br>
                            <p class="tab"></p>
                            <b>Web History</b><br>
                            <input type="checkbox" id="prsAmazon" checked>Amazon Purchases<br>
                            <p class="tab"></p>
                            <b>Personal Records</b><br>
                            
                            <input type="checkbox" id="prsRace" checked>Race<br>
                            <input type="checkbox" id="prsGender" checked >Gender<br>
                            <input type="checkbox" id="prsSexuality" checked >Sexuality<br>
                            <input type="checkbox" id="prsCrimes" checked>Criminal Record<br><p></p>
                            
                            <b>Financial Data</b><br>
                            
                            <input type="checkbox" id="prsSalary" checked>Current Salary<br>
                            
                        </div>
                        
                    
                </div>
            </td>
            
        </tr>
        </table>
        <% if current_user %>
        <table class="results_history">
        <% @history = Useraction.where('action_category = ? AND user_id = ?', 'solution', current_user.first_name).order('id DESC').limit(5) %>
        <% @history.each_with_index do |history_record, i| %>
            
            <tr>
                <td>
                <span>History of Results <%= i %> </span> 
                <% history_array = history_record.action_details.split('-', -1) %>
                </td>
                <td>
                    <div  class="level3">
                        <div class="lvl3Results">
                        <h2>Results:</h2>
                        <p>Extreme Poverty:</p>
                        <p>White: <span><%= history_array[18] %></span>%<br/>Color: <span><%= history_array[19] %></span>%</p>
                        <p>Male: <span><%= history_array[20] %></span>%<br/>Female: <span><%= history_array[21] %></span>%</p>
                    
                        </div>

                    </div>
                
                </td>

                <td class="level3">
                    <div class="level3">
                            <div class="lvl3CompanySelectors">
                                <u><b>Data for Job Application</b></u><br>
                                <p class="tab"></p>
                                <b>Web History</b><br>
                                <input type="checkbox" <%= history_array[0] %> disabled="true">Amazon Purchases<br>
                                <p class="tab"></p>
                                <b>Personal Records</b><br>
                                
                                <input type="checkbox"  <%= history_array[1] %> disabled="true">Race<br>
                                <input type="checkbox"  <%= history_array[2] %> disabled="true">Gender<br>
                                <input type="checkbox"  <%= history_array[3] %> disabled="true">Sexuality<br>
                                <input type="checkbox"  <%= history_array[4] %> disabled="true">Criminal Record<br><p></p>
                                
                                <b>Financial Data</b><br>
                            
                                <input type="checkbox"  <%= history_array[5] %> disabled="true">Current Salary<br>
                                
                            </div>
                    </div>
                </td>
                <td class="level3">
                    <div class="level3">
                        
                        
                            
                        <div class="lvl3BankSelectors">
                            <u><b>Data for Bank Loan</b></u><br>
                            <p class="tab"></p>
                            <b>Web History</b><br>
                            <input type="checkbox"  <%= history_array[6] %> disabled="true">Amazon Purchases<br>
                            <p class="tab"></p>
                            <b>Personal Records</b><br>
                            
                            <input type="checkbox"  <%= history_array[7] %> disabled="true">Race<br>
                            <input type="checkbox"  <%= history_array[8] %> disabled="true">Gender<br>
                            <input type="checkbox"  <%= history_array[9] %> disabled="true">Sexuality<br>
                            <input type="checkbox"  <%= history_array[10] %> disabled="true">Criminal Record<br><p></p>
                            
                            <b>Financial Data</b><br>
                            
                            <input type="checkbox"  <%= history_array[11] %> disabled="true">Current Salary<br>
                            
                        </div>
                    </div>
                </td>
                <td class="level3">
                    <div class="level3">            
                            <div class="lvl3PrisonSelectors">
                                <u><b>Data for Prison Sentence</b></u><br>
                                <p class="tab"></p>
                                <b>Web History</b><br>
                                <input type="checkbox"  <%= history_array[12] %> disabled="true">Amazon Purchases<br>
                                <p class="tab"></p>
                                <b>Personal Records</b><br>
                                
                                <input type="checkbox"  <%= history_array[13] %> disabled="true">Race<br>
                                <input type="checkbox"  <%= history_array[14] %> disabled="true">Gender<br>
                                <input type="checkbox"  <%= history_array[15] %> disabled="true">Sexuality<br>
                                <input type="checkbox"  <%= history_array[16] %> disabled="true">Criminal Record<br><p></p>
                                
                                <b>Financial Data</b><br>
                                
                                <input type="checkbox"  <%= history_array[17] %> disabled="true">Current Salary<br>
                                
                            </div>
                            
                        
                    </div>
                </td>
            </tr>
            
            <% end %>
            </table>
        <% end %>
   

app/views/page/index.html.erb
<h1>Page#index</h1>
come on to <a href="lvl1">Level 1</a>, <a href="lvl2">Level 2</a>, or <a href="lvl3">Level 3</a>!
<p>Find me in app/views/page/index.html.erb</p>

app/views/useraction/create.html.erb
<h1>Useraction#create</h1>
<p>Find me in app/views/useraction/create.html.erb</p>

app/views/useraction/destroy.html.erb
<h1>Useraction#destroy</h1>
<p>Find me in app/views/useraction/destroy.html.erb</p>

app/views/useraction/new.html.erb
<h1>Useraction#new</h1>
<p>Find me in app/views/useraction/new.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<%= render @user %>


<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

<div>
Full user history:
 <% @fullhistory = Useraction.where('user_id = ?', current_user.first_name).order('id ASC') %>
 <% @fullhistory.each_with_index do |history_record, i| %>
    <span> <%= history_record.id %>, <%= history_record.user_id %>, <%= history_record.level %>, <%= history_record.action_category %>, <%= history_record.action_details %>, <%= history_record.created_at %>
    <br />
 <% end %>
</div>